version: "2.3"
services:

  pepperhri:
    image: pepper-hri
    container_name: pepperhri
    tty: true
    ipc: host
    network_mode: "host"
    privileged: true
    security_opt:
      - seccomp:unconfined
    environment:
      - PULSE_SERVER=unix:/mnt/wslg/PulseServer
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - PEPPER_TOOLS_HOME=/home/robot/src/pepper_tools
      - MODIM_HOME=/home/robot/src/modim
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/robot/.Xauthority
      - /mnt/wslg:/mnt/wslg
      - ${HOME}/playground:/home/robot/playground
      - $HOME/src/Pepper/pepper_tools:/home/robot/src/pepper_tools
      - $HOME/src/Pepper/modim:/home/robot/src/modim
    working_dir: /home/robot/
    entrypoint:
      - bash
      - -ci
      - "cd /home/robot/ && ./init.bash"
